### ISSUE TITLE
 Missing required key 'Value' in params.Tags[0]

### ISSUE THREAD

**Issue by asafdavid230** [trek10inc/serverless-cloudformation-changesets#20]
Hi, I'm trying to run the serverless deploy command without any flag and getting this error:
`Missing required key 'Value' in params.Tags[0]`
with the following custom block:
```
custom:
  inputBucket: input-bucket-111223344 # Change to unique name
  outputBucket: output-bucket-bucket26111990 # Change to unique name
  cf-changesets:
    requireChangeSet: true # optional defaults to false
```

After a short look in the plugin code I found the following variable:
```
  let stackTags = {
    STAGE: plugin.options.stage
  }
```
looks like it is required to be sent from the CLI argument for `stage`

in my case, I'm using `yaml` file definitions, (for `stage` too).
how can I deal with it?
