### ISSUE TITLE
Enable plugin via `custom` option in serverless.yml

### ISSUE THREAD

**Issue by hassankhan** [trek10inc/serverless-cloudformation-changesets#4]
As well as being able to set it via CLI?

**Comment by shortjared** [comment]
We are thinking 

I would say the configuration should be
```
custom:
  serverless-cloudformation-changesets:
    changeSetName: whatever # optional
    requireChangeSet: boolean # optional defaults to false
```

@hassankhan, how's that look to you?

**Comment by shortjared** [comment]
I think that makes sense.

**Comment by shortjared** [comment]
@modmac can you handle this please?

```yaml
custom:
  cf-changesets:
    changeSetName: whatever # optional
    requireChangeSet: boolean # optional defaults to false
```
